services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: rag-backend:latest
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/code/data
      - ./chroma_db:/code/chroma_db
      - ./logs:/code/logs
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rag-frontend:latest
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    restart: unless-stopped