services:
  # Backend Service
  - type: web
    name: rag-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "false"
      - key: LANGCHAIN_API_KEY
        sync: false
    healthCheckPath: /api/v1/health
    
  # Frontend Service  
  - type: web
    name: rag-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: API_BASE_URL
        fromService:
          name: rag-backend
          type: web
          property: host
          envVarKey: API_BASE_URL

  # Persistent Disk for Vector Store
  - type: pserv
    name: rag-data
    env: docker
    disk:
      name: chroma-data
      mountPath: /data
      sizeGB: 10